//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsUpWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public int WordId { get; set; }
        public int UserId { get; set; }
        public int Count { get; set; }
    
        public virtual Word Word { get; set; }
        public virtual User User { get; set; }
    }
}
